// ─── Dynamic styles factory ───
export const getStyles = (colors) => ({
    app: {
        fontFamily: "'Georgia', 'Palatino', 'Times New Roman', serif",
        background: colors.bg,
        minHeight: "100vh",
        maxWidth: 480,
        margin: "0 auto",
        position: "relative",
        overflow: "hidden",
        WebkitFontSmoothing: "antialiased",
        transition: "background 0.3s",
    },
    splashScreen: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
        background: colors.bg,
        transition: "background 0.3s",
    },
    toast: {
        position: "fixed",
        top: "calc(env(safe-area-inset-top, 0px) + 12px)",
        left: "50%",
        transform: "translateX(-50%)",
        background: colors.text,
        color: colors.bg,
        padding: "10px 20px",
        borderRadius: 20,
        fontSize: 14,
        zIndex: 1000,
        boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
        animation: "toastSlideDown 0.3s ease",
        display: "flex",
        alignItems: "center",
        gap: 12,
        whiteSpace: "nowrap",
    },
    toastActionBtn: {
        background: "none",
        border: "none",
        color: colors.accent,
        fontWeight: 700,
        fontSize: 14,
        cursor: "pointer",
        padding: "2px 4px",
        textDecoration: "underline",
        fontFamily: "inherit",
    },
    screen: {
        padding: "calc(env(safe-area-inset-top, 0px) + 16px) 16px 100px 16px",
        overflowY: "auto",
        minHeight: "100vh",
    },

    // Home
    homeHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 20,
        paddingTop: 8,
    },
    brandName: {
        fontSize: 28,
        fontWeight: 700,
        color: colors.text,
        margin: 0,
        letterSpacing: -0.5,
        fontFamily: "'Georgia', serif",
    },
    brandSub: { color: colors.textLight, fontSize: 13, marginTop: 4, fontFamily: "system-ui, sans-serif" },
    iconBtn: {
        background: colors.warm,
        border: "none",
        borderRadius: 12,
        width: 42,
        height: 42,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        position: "relative",
        color: colors.text,
    },
    badge: {
        position: "absolute",
        top: -2,
        right: -2,
        background: colors.accent,
        color: "#fff",
        fontSize: 10,
        fontWeight: 700,
        width: 18,
        height: 18,
        borderRadius: 9,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "system-ui",
    },

    // Search
    searchWrap: {
        position: "relative",
        marginBottom: 16,
    },
    searchIcon: {
        position: "absolute",
        left: 14,
        top: "50%",
        transform: "translateY(-50%)",
    },
    searchInput: {
        width: "100%",
        padding: "13px 40px 13px 42px",
        borderRadius: 14,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        fontSize: 15,
        color: colors.text,
        fontFamily: "system-ui, sans-serif",
        outline: "none",
        boxSizing: "border-box",
        transition: "border-color 0.2s",
    },
    searchClear: {
        position: "absolute",
        right: 12,
        top: "50%",
        transform: "translateY(-50%)",
        background: "none",
        border: "none",
        cursor: "pointer",
        color: colors.textLight,
        padding: 4,
    },

    // Pills
    pillRow: {
        display: "flex",
        gap: 8,
        overflowX: "auto",
        paddingBottom: 16,
        WebkitOverflowScrolling: "touch",
        scrollbarWidth: "none",
        msOverflowStyle: "none",
    },
    pill: {
        flexShrink: 0,
        padding: "8px 14px",
        borderRadius: 20,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        color: colors.textMid,
        fontSize: 13,
        fontFamily: "system-ui, sans-serif",
        fontWeight: 500,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        transition: "all 0.2s",
        whiteSpace: "nowrap",
    },
    pillActive: {
        background: colors.accent,
        color: "#fff",
        borderColor: colors.accent,
    },

    // Recipe cards
    recipeGrid: {
        display: "flex",
        flexDirection: "column",
        gap: 12,
    },
    recipeCard: {
        background: colors.card,
        borderRadius: 16,
        padding: 16,
        border: `1.5px solid ${colors.border}`,
        cursor: "pointer",
        textAlign: "left",
        transition: "all 0.2s",
        width: "100%",
        boxSizing: "border-box",
    },
    cardTop: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    cardCategory: {
        fontSize: 11,
        fontWeight: 600,
        color: colors.accent,
        textTransform: "uppercase",
        letterSpacing: 0.8,
        fontFamily: "system-ui, sans-serif",
    },
    cardFavBtn: {
        background: "none",
        border: "none",
        cursor: "pointer",
        padding: 2,
    },
    cardTitle: {
        fontSize: 17,
        fontWeight: 600,
        color: colors.text,
        margin: "0 0 8px",
        lineHeight: 1.3,
        fontFamily: "'Georgia', serif",
    },
    cardMeta: {
        display: "flex",
        gap: 16,
        fontSize: 12,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
    },
    cardMetaItem: {
        display: "flex",
        alignItems: "center",
        gap: 4,
    },
    cardCooked: {
        fontSize: 11,
        color: colors.textLight,
        marginTop: 8,
        fontFamily: "system-ui, sans-serif",
    },
    cardTags: {
        display: "flex",
        gap: 6,
        marginTop: 8,
        flexWrap: "wrap",
    },
    cardTag: {
        fontSize: 11,
        color: colors.accent,
        fontFamily: "system-ui, sans-serif",
    },
    emptyState: {
        textAlign: "center",
        padding: "48px 20px",
    },

    // FAB
    fab: {
        position: "fixed",
        bottom: 24,
        right: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        background: colors.accent,
        border: "none",
        boxShadow: "0 4px 20px rgba(212, 119, 91, 0.4)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        zIndex: 100,
        transition: "transform 0.2s",
    },
    fabOverlay: {
        position: "fixed",
        inset: 0,
        zIndex: 99,
        background: "rgba(0,0,0,0.3)",
        animation: "backdropFadeIn 0.2s ease",
    },
    fabMenu: {
        position: "fixed",
        bottom: 92,
        right: 24,
        zIndex: 101,
        display: "flex",
        flexDirection: "column",
        gap: 12,
        alignItems: "flex-end",
        animation: "fadeIn 0.2s ease",
    },
    fabMenuRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
    },
    fabMenuLabel: {
        background: colors.text,
        color: colors.bg,
        padding: "6px 12px",
        borderRadius: 8,
        fontSize: 13,
        fontWeight: 600,
        fontFamily: "system-ui, sans-serif",
        whiteSpace: "nowrap",
        boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
    },
    fabMini: {
        width: 46,
        height: 46,
        borderRadius: 23,
        background: colors.accent,
        border: "none",
        boxShadow: "0 2px 12px rgba(212,119,91,0.3)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
    },
    importLoadingOverlay: {
        position: "fixed",
        inset: 0,
        zIndex: 500,
        background: "rgba(0,0,0,0.5)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        animation: "backdropFadeIn 0.2s ease",
    },
    importLoadingCard: {
        background: colors.card,
        borderRadius: 20,
        padding: "32px 40px",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 16,
        boxShadow: "0 8px 32px rgba(0,0,0,0.2)",
    },
    importLoadingTitle: {
        fontSize: 16,
        fontWeight: 600,
        color: colors.text,
        fontFamily: "'Georgia', serif",
    },
    importLoadingSubtitle: {
        fontSize: 13,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
    },
    urlImportOverlay: {
        position: "fixed",
        inset: 0,
        zIndex: 500,
        background: "rgba(0,0,0,0.5)",
        animation: "backdropFadeIn 0.2s ease",
    },
    urlImportModal: {
        position: "fixed",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -50%)",
        zIndex: 501,
        background: colors.card,
        borderRadius: 20,
        padding: "28px 24px",
        width: "calc(100% - 48px)",
        maxWidth: 400,
        boxShadow: "0 8px 32px rgba(0,0,0,0.2)",
        animation: "fadeIn 0.2s ease",
        boxSizing: "border-box",
    },
    urlImportTitle: {
        fontSize: 18,
        fontWeight: 700,
        color: colors.text,
        margin: "0 0 6px",
        fontFamily: "'Georgia', serif",
    },
    urlImportSubtitle: {
        fontSize: 13,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
        margin: "0 0 16px",
    },

    // Detail view
    detailNav: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
        paddingTop: 4,
    },
    backBtn: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        background: "none",
        border: "none",
        fontSize: 15,
        color: colors.accent,
        cursor: "pointer",
        fontFamily: "system-ui, sans-serif",
        fontWeight: 500,
        padding: 0,
    },
    iconBtnSmall: {
        background: colors.warm,
        border: "none",
        borderRadius: 10,
        width: 36,
        height: 36,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        color: colors.textMid,
    },
    detailHeader: {
        marginBottom: 20,
    },
    detailCategoryPill: {
        display: "inline-block",
        fontSize: 11,
        fontWeight: 600,
        color: colors.accent,
        textTransform: "uppercase",
        letterSpacing: 0.8,
        marginBottom: 8,
        fontFamily: "system-ui, sans-serif",
    },
    detailTitle: {
        fontSize: 26,
        fontWeight: 700,
        color: colors.text,
        margin: "0 0 16px",
        lineHeight: 1.2,
        fontFamily: "'Georgia', serif",
    },
    detailStats: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-around",
        background: colors.warm,
        borderRadius: 14,
        padding: "14px 8px",
    },
    statBox: { textAlign: "center" },
    statValue: {
        fontSize: 18,
        fontWeight: 700,
        color: colors.text,
        fontFamily: "system-ui, sans-serif",
    },
    statLabel: {
        fontSize: 11,
        color: colors.textLight,
        marginTop: 2,
        fontFamily: "system-ui, sans-serif",
    },
    statDivider: {
        width: 1,
        height: 30,
        background: colors.border,
    },

    // Scale
    scaleSection: {
        margin: "16px 0",
        display: "flex",
        alignItems: "center",
        gap: 12,
        justifyContent: "space-between",
    },
    scaleLabel: {
        fontSize: 13,
        color: colors.textMid,
        fontFamily: "system-ui, sans-serif",
        display: "flex",
        alignItems: "center",
        gap: 6,
        fontWeight: 500,
        flexShrink: 0,
    },
    scaleButtons: {
        display: "flex",
        gap: 6,
    },
    scaleBtn: {
        padding: "7px 12px",
        borderRadius: 10,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        fontSize: 13,
        fontWeight: 600,
        color: colors.textMid,
        cursor: "pointer",
        fontFamily: "system-ui, sans-serif",
        transition: "all 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
    },
    scaleBtnActive: {
        background: colors.accent,
        color: "#fff",
        borderColor: colors.accent,
    },

    // Sections
    section: {
        marginBottom: 20,
    },
    sectionHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 700,
        color: colors.text,
        margin: 0,
        fontFamily: "'Georgia', serif",
    },
    shopBtn: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "7px 12px",
        borderRadius: 10,
        border: `1.5px solid ${colors.accent}`,
        background: "transparent",
        color: colors.accent,
        fontSize: 12,
        fontWeight: 600,
        cursor: "pointer",
        fontFamily: "system-ui, sans-serif",
    },

    // Ingredients
    ingredientsList: {
        background: colors.card,
        borderRadius: 14,
        border: `1.5px solid ${colors.border}`,
        overflow: "hidden",
    },
    ingredientRow: {
        display: "flex",
        alignItems: "center",
        padding: "11px 14px",
        borderBottom: `1px solid ${colors.border}`,
        fontSize: 14,
        fontFamily: "system-ui, sans-serif",
    },
    ingredientAmount: {
        fontWeight: 600,
        color: colors.accent,
        minWidth: 90,
        fontSize: 13,
    },
    ingredientName: {
        color: colors.text,
    },

    // Instructions
    instructions: {
        background: colors.card,
        borderRadius: 14,
        border: `1.5px solid ${colors.border}`,
        padding: 16,
    },
    instructionLine: {
        fontSize: 14,
        lineHeight: 1.7,
        color: colors.text,
        margin: "0 0 8px",
        fontFamily: "system-ui, sans-serif",
    },

    // Notes
    notesText: {
        background: colors.warm,
        borderRadius: 14,
        padding: 16,
        fontSize: 14,
        lineHeight: 1.6,
        color: colors.textMid,
        fontStyle: "italic",
        margin: 0,
        fontFamily: "'Georgia', serif",
    },

    // Tags
    tagsRow: {
        display: "flex",
        gap: 8,
        flexWrap: "wrap",
    },
    detailTag: {
        padding: "6px 12px",
        borderRadius: 16,
        background: colors.warm,
        fontSize: 12,
        color: colors.textMid,
        fontFamily: "system-ui, sans-serif",
    },

    // Actions
    detailActions: {
        display: "flex",
        gap: 12,
        marginTop: 8,
    },
    actionBtn: {
        flex: 1,
        padding: "13px 16px",
        borderRadius: 14,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        fontSize: 14,
        fontWeight: 600,
        color: colors.textMid,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        fontFamily: "system-ui, sans-serif",
    },
    actionBtnPrimary: {
        background: colors.accent,
        color: "#fff",
        borderColor: colors.accent,
    },

    // Edit form
    editTitle: {
        fontSize: 24,
        fontWeight: 700,
        color: colors.text,
        margin: "0 0 20px",
        fontFamily: "'Georgia', serif",
    },
    saveBtn: {
        padding: "9px 20px",
        borderRadius: 10,
        border: "none",
        background: colors.accent,
        color: "#fff",
        fontSize: 14,
        fontWeight: 600,
        cursor: "pointer",
        fontFamily: "system-ui, sans-serif",
    },
    formGroup: {
        marginBottom: 16,
    },
    formLabel: {
        display: "block",
        fontSize: 12,
        fontWeight: 600,
        color: colors.textMid,
        marginBottom: 6,
        textTransform: "uppercase",
        letterSpacing: 0.5,
        fontFamily: "system-ui, sans-serif",
    },
    formInput: {
        width: "100%",
        padding: "11px 14px",
        borderRadius: 10,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        fontSize: 15,
        color: colors.text,
        fontFamily: "system-ui, sans-serif",
        outline: "none",
        boxSizing: "border-box",
    },
    formSelect: {
        width: "100%",
        padding: "11px 14px",
        borderRadius: 10,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        fontSize: 15,
        color: colors.text,
        fontFamily: "system-ui, sans-serif",
        outline: "none",
        boxSizing: "border-box",
        appearance: "auto",
    },
    formTextarea: {
        width: "100%",
        padding: "11px 14px",
        borderRadius: 10,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        fontSize: 15,
        color: colors.text,
        fontFamily: "system-ui, sans-serif",
        outline: "none",
        boxSizing: "border-box",
        resize: "vertical",
        lineHeight: 1.6,
    },
    ingEditRow: {
        display: "flex",
        gap: 6,
        marginBottom: 8,
        alignItems: "center",
    },
    ingRemoveBtn: {
        background: "none",
        border: "none",
        cursor: "pointer",
        padding: 4,
        flexShrink: 0,
    },
    addIngBtn: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "10px 14px",
        borderRadius: 10,
        border: `1.5px dashed ${colors.border}`,
        background: "transparent",
        fontSize: 13,
        fontWeight: 500,
        color: colors.textMid,
        cursor: "pointer",
        width: "100%",
        justifyContent: "center",
        fontFamily: "system-ui, sans-serif",
        marginTop: 4,
    },

    // Shopping list
    shoppingItems: {
        display: "flex",
        flexDirection: "column",
        gap: 8,
    },
    shoppingItem: {
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "12px 14px",
        borderRadius: 12,
        background: colors.card,
        border: `1.5px solid ${colors.border}`,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    shoppingItemChecked: {
        background: colors.warm,
    },
    checkbox: {
        width: 22,
        height: 22,
        borderRadius: 6,
        border: `2px solid ${colors.border}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        transition: "all 0.2s",
    },
    checkboxChecked: {
        background: colors.accent,
        borderColor: colors.accent,
    },
    shoppingItemName: {
        fontSize: 14,
        color: colors.text,
        fontFamily: "system-ui, sans-serif",
        display: "block",
    },
    shoppingItemRecipe: {
        fontSize: 11,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
        display: "block",
        marginTop: 2,
    },

    // Suggest
    suggestCard: {
        display: "block",
        width: "100%",
        padding: 16,
        borderRadius: 14,
        background: colors.card,
        border: `1.5px solid ${colors.border}`,
        marginBottom: 10,
        cursor: "pointer",
        textAlign: "left",
        transition: "all 0.2s",
    },
    suggestTop: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 4,
    },
    suggestName: {
        fontSize: 16,
        fontWeight: 600,
        color: colors.text,
        margin: 0,
        fontFamily: "'Georgia', serif",
    },
    matchBadge: {
        padding: "4px 10px",
        borderRadius: 12,
        background: colors.accent,
        color: "#fff",
        fontSize: 12,
        fontWeight: 600,
        fontFamily: "system-ui, sans-serif",
    },
    suggestMeta: {
        fontSize: 12,
        color: colors.textLight,
        margin: 0,
        fontFamily: "system-ui, sans-serif",
    },

    // Calendar
    calendarMonthBar: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    calendarMonthBtn: {
        width: 34,
        height: 34,
        borderRadius: 10,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        color: colors.textMid,
    },
    calendarMonthLabel: {
        fontSize: 18,
        fontWeight: 700,
        color: colors.text,
        fontFamily: "'Georgia', serif",
    },
    calendarWeekRow: {
        display: "grid",
        gridTemplateColumns: "repeat(7, 1fr)",
        gap: 6,
        marginBottom: 6,
    },
    calendarWeekCell: {
        textAlign: "center",
        fontSize: 11,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.4,
    },
    calendarGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(7, 1fr)",
        gap: 6,
        marginBottom: 14,
    },
    calendarEmptyCell: {
        minHeight: 44,
    },
    calendarDay: {
        minHeight: 44,
        borderRadius: 12,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        color: colors.text,
        fontSize: 14,
        fontFamily: "system-ui, sans-serif",
        cursor: "pointer",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        padding: "4px 2px",
        position: "relative",
    },
    calendarDayToday: {
        borderColor: colors.accent,
    },
    calendarDaySelected: {
        background: colors.warm,
        borderColor: colors.accent,
        color: colors.accentDark,
    },
    calendarDayCount: {
        fontSize: 10,
        fontWeight: 700,
        lineHeight: 1,
        color: colors.accent,
        fontFamily: "system-ui, sans-serif",
    },
    calendarSelectedDate: {
        fontSize: 13,
        color: colors.textMid,
        fontFamily: "system-ui, sans-serif",
        margin: "4px 2px 8px",
    },
    calendarEntriesList: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
        marginBottom: 20,
    },
    calendarEntryCard: {
        borderRadius: 14,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        padding: 12,
    },
    calendarEntryTop: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: 8,
    },
    calendarEntryTitle: {
        fontSize: 15,
        color: colors.text,
        fontWeight: 700,
        fontFamily: "'Georgia', serif",
    },
    calendarEntryTime: {
        fontSize: 11,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
        marginTop: 2,
    },
    calendarEntryDelete: {
        background: "none",
        border: "none",
        cursor: "pointer",
        padding: 2,
        flexShrink: 0,
    },
    calendarEntryNotes: {
        margin: "8px 0 0",
        fontSize: 13,
        lineHeight: 1.5,
        color: colors.textMid,
        fontFamily: "system-ui, sans-serif",
    },
    calendarEntryPhotos: {
        marginTop: 10,
        display: "grid",
        gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
        gap: 8,
    },
    calendarEntryPhoto: {
        width: "100%",
        height: 88,
        objectFit: "cover",
        borderRadius: 10,
        display: "block",
        background: colors.warm,
    },
    addBakePhotoBtn: {
        width: "100%",
        padding: "11px 14px",
        borderRadius: 10,
        border: `1.5px dashed ${colors.border}`,
        background: colors.warm,
        fontSize: 14,
        color: colors.textMid,
        fontFamily: "system-ui, sans-serif",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
    },
    bakePhotoPreviewRow: {
        display: "grid",
        gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
        gap: 8,
        marginTop: 10,
    },
    bakePhotoPreviewWrap: {
        position: "relative",
    },
    bakePhotoPreview: {
        width: "100%",
        height: 64,
        objectFit: "cover",
        borderRadius: 10,
        display: "block",
        background: colors.warm,
    },
    bakePhotoRemoveBtn: {
        position: "absolute",
        top: 4,
        right: 4,
        width: 18,
        height: 18,
        borderRadius: 9,
        border: "none",
        background: "rgba(0,0,0,0.7)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        padding: 0,
    },

    // ─── Cooking Mode ───
    startCookingBtn: {
        width: "100%",
        padding: "16px 20px",
        borderRadius: 16,
        border: "none",
        background: `linear-gradient(135deg, ${colors.accent}, ${colors.accentDark})`,
        color: "#fff",
        fontSize: 17,
        fontWeight: 700,
        cursor: "pointer",
        fontFamily: "'Georgia', serif",
        marginBottom: 12,
        letterSpacing: 0.3,
        boxShadow: "0 4px 16px rgba(212,119,91,0.3)",
    },
    cookingScreen: {
        position: "fixed",
        inset: 0,
        zIndex: 200,
        background: colors.bg,
        display: "flex",
        flexDirection: "column",
        padding: "calc(env(safe-area-inset-top, 0px) + 16px) 20px env(safe-area-inset-bottom)",
        maxWidth: 480,
        margin: "0 auto",
        boxSizing: "border-box",
    },
    cookingTopBar: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    cookingStepCount: {
        fontSize: 13,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
        fontWeight: 600,
    },
    cookingRecipeName: {
        fontSize: 14,
        color: colors.textMid,
        fontFamily: "system-ui, sans-serif",
        marginBottom: 12,
        textAlign: "center",
    },
    cookingProgress: {
        display: "flex",
        gap: 3,
        marginBottom: 24,
    },
    cookingStepContent: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "0 8px",
        textAlign: "center",
    },
    cookingStepNumber: {
        fontSize: 13,
        fontWeight: 700,
        color: colors.accent,
        fontFamily: "system-ui, sans-serif",
        textTransform: "uppercase",
        letterSpacing: 1,
        marginBottom: 16,
    },
    cookingStepText: {
        fontSize: 22,
        lineHeight: 1.5,
        color: colors.text,
        fontFamily: "'Georgia', serif",
        margin: 0,
        fontWeight: 500,
    },
    cookingTimerBtn: {
        marginTop: 20,
        padding: "10px 20px",
        borderRadius: 12,
        border: `1.5px solid ${colors.accent}`,
        background: "transparent",
        color: colors.accent,
        fontSize: 14,
        fontWeight: 600,
        cursor: "pointer",
        fontFamily: "system-ui, sans-serif",
        display: "flex",
        alignItems: "center",
        gap: 8,
    },
    cookingNav: {
        display: "flex",
        gap: 12,
        marginTop: 20,
    },
    cookingNavBtn: {
        flex: 1,
        padding: "14px 16px",
        borderRadius: 14,
        border: `1.5px solid ${colors.border}`,
        background: colors.card,
        fontSize: 15,
        fontWeight: 600,
        color: colors.textMid,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        fontFamily: "system-ui, sans-serif",
    },
    cookingNavBtnPrimary: {
        background: colors.accent,
        color: "#fff",
        borderColor: colors.accent,
    },

    // ─── Timer Pill ───
    timerPillContainer: {
        position: "fixed",
        bottom: 90,
        left: "50%",
        transform: "translateX(-50%)",
        zIndex: 150,
        display: "flex",
        flexDirection: "column",
        gap: 6,
        alignItems: "center",
    },
    timerPill: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        padding: "8px 14px",
        borderRadius: 20,
        background: colors.text,
        color: colors.bg,
        fontSize: 13,
        fontFamily: "system-ui, sans-serif",
        fontWeight: 600,
        boxShadow: "0 4px 20px rgba(0,0,0,0.2)",
        backdropFilter: "blur(8px)",
        whiteSpace: "nowrap",
    },
    timerPillLabel: {
        maxWidth: 100,
        overflow: "hidden",
        textOverflow: "ellipsis",
        fontSize: 12,
        opacity: 0.8,
    },
    timerPillTime: {
        fontVariantNumeric: "tabular-nums",
        fontSize: 15,
        fontWeight: 700,
        minWidth: 36,
    },
    timerPillBtn: {
        background: "none",
        border: "none",
        color: colors.bg,
        fontSize: 14,
        cursor: "pointer",
        padding: "0 2px",
        opacity: 0.8,
    },

    // ─── Bottom Sheet ───
    bottomSheetBackdrop: {
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.4)",
        zIndex: 300,
        animation: "backdropFadeIn 0.2s ease",
    },
    bottomSheet: {
        position: "fixed",
        bottom: 0,
        left: 0,
        right: 0,
        maxWidth: 480,
        margin: "0 auto",
        background: colors.card,
        borderRadius: "20px 20px 0 0",
        padding: "12px 20px calc(20px + env(safe-area-inset-bottom))",
        zIndex: 301,
        animation: "bottomSheetUp 0.3s ease",
    },
    bottomSheetHandle: {
        width: 36,
        height: 4,
        borderRadius: 2,
        background: colors.border,
        margin: "0 auto 16px",
    },
    bottomSheetTitle: {
        fontSize: 16,
        fontWeight: 700,
        color: colors.text,
        fontFamily: "'Georgia', serif",
        marginBottom: 16,
        textAlign: "center",
    },
    bottomSheetAction: {
        width: "100%",
        display: "flex",
        alignItems: "center",
        gap: 14,
        padding: "14px 4px",
        background: "none",
        border: "none",
        borderTop: `1px solid ${colors.border}`,
        fontSize: 15,
        fontWeight: 500,
        color: colors.text,
        cursor: "pointer",
        fontFamily: "system-ui, sans-serif",
        textAlign: "left",
    },

    // ─── Sort Pills ───
    sortPill: {
        flexShrink: 0,
        padding: "5px 11px",
        borderRadius: 14,
        border: `1px solid ${colors.border}`,
        background: "transparent",
        color: colors.textLight,
        fontSize: 11,
        fontFamily: "system-ui, sans-serif",
        fontWeight: 600,
        cursor: "pointer",
        transition: "all 0.2s",
        whiteSpace: "nowrap",
    },
    sortPillActive: {
        background: colors.warmDark,
        color: colors.text,
        borderColor: colors.warmDark,
    },

    // ─── Recently Viewed ───
    recentRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        overflowX: "auto",
        paddingBottom: 12,
        WebkitOverflowScrolling: "touch",
        scrollbarWidth: "none",
        msOverflowStyle: "none",
    },
    recentLabel: {
        fontSize: 11,
        fontWeight: 600,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
        flexShrink: 0,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    recentItem: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 4,
        background: "none",
        border: "none",
        cursor: "pointer",
        flexShrink: 0,
        padding: 0,
    },
    recentAvatar: {
        width: 48,
        height: 48,
        borderRadius: "50%",
        background: colors.warm,
        border: `2px solid ${colors.border}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
    },
    recentName: {
        fontSize: 10,
        color: colors.textLight,
        fontFamily: "system-ui, sans-serif",
        maxWidth: 52,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
});
